---
language: "python"

jobs:
  include:
    # There's no Docker image for 1.0.0b3 unfortunately
    # - python: "3.6"
    #   env: "INVOKE_NAUTOBOT_NETBOX_IMPORTER_NAUTOBOT_VER=1.0.0b3"
    - python: "3.6"
      env: "INVOKE_NAUTOBOT_NETBOX_IMPORTER_NAUTOBOT_VER=1.0.0"
    - python: "3.7"
      env: "INVOKE_NAUTOBOT_NETBOX_IMPORTER_NAUTOBOT_VER=1.0.0"
    - python: "3.8"
      env: "INVOKE_NAUTOBOT_NETBOX_IMPORTER_NAUTOBOT_VER=1.0.0"
    # TODO: Failing at the moment, will troubleshoot later
    # - python: "3.8"
    #   env: "INVOKE_NAUTOBOT_NETBOX_IMPORTER_NAUTOBOT_VER=develop-latest"

services:
  - "docker"

# --------------------------------------------------------------------------
# Tests
# --------------------------------------------------------------------------
before_script:
  - "pip install invoke toml docker-compose poetry"
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin || travis_terminate 1  # yamllint disable-line rule:quoted-strings
  - "cp development/creds.example.env development/creds.env"

script:
  - "INVOKE_NAUTOBOT_NETBOX_IMPORTER_PYTHON_VER=$TRAVIS_PYTHON_VERSION invoke build --no-cache"
  - "INVOKE_NAUTOBOT_NETBOX_IMPORTER_PYTHON_VER=$TRAVIS_PYTHON_VERSION invoke tests"

deploy:
  provider: script
  script:
    - poetry config pypi-token.pypi $PYPI_TOKEN
    - poetry publish --build
  skip_cleanup: true
  on:
    tags: true
    branch: master
    condition: $INVOKE_NAUTOBOT_NETBOX_IMPORTER_NAUTOBOT_VER = 1.0.0
    python: 3.7
